package com.bookflow.businesses.members.repository;
import com.bookflow.businesses.members.api.MemberResponse; import com.bookflow.businesses.members.application.MemberConflictException; import org.springframework.context.annotation.Profile; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository @Profile("!test") public class JdbcMemberRepository implements MemberRepository {
 private final JdbcTemplate jdbc; public JdbcMemberRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 private static final String C="m.id,m.user_id,u.normalized_email,m.role,m.status,e.id employee_id,m.created_at,m.updated_at FROM business_memberships m JOIN users u ON u.id=m.user_id LEFT JOIN employees e ON e.tenant_id=m.tenant_id AND e.user_id=m.user_id";
 public List<MemberResponse> list(UUID t){return jdbc.query("SELECT "+C+" WHERE m.tenant_id=? ORDER BY m.created_at,m.id",this::map,t);} public Optional<MemberResponse> byId(UUID t,UUID id){return jdbc.query("SELECT "+C+" WHERE m.tenant_id=? AND m.id=?",this::map,t,id).stream().findFirst();}
 public Optional<UUID> userByEmail(String e){return jdbc.queryForList("SELECT id FROM users WHERE normalized_email=? AND status='ACTIVE'",UUID.class,e).stream().findFirst();} public boolean activeEmployee(UUID t,UUID e){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM employees WHERE tenant_id=? AND id=? AND status='ACTIVE')",Boolean.class,t,e));}
 public MemberResponse invite(UUID t,UUID u,String r,UUID e){ try {return jdbc.query("INSERT INTO business_memberships(id,tenant_id,user_id,role,status,revoked_at,revoked_by) VALUES(?,?,?,?, 'ACTIVE',NULL,NULL) ON CONFLICT(user_id,tenant_id) DO UPDATE SET role=EXCLUDED.role,status='ACTIVE',revoked_at=NULL,revoked_by=NULL,updated_at=CURRENT_TIMESTAMP WHERE business_memberships.status='REVOKED' RETURNING id,user_id,(SELECT normalized_email FROM users WHERE id=user_id),role,status,?::uuid AS employee_id,created_at,updated_at",this::map,UUID.randomUUID(),t,u,r,e).stream().findFirst().orElseThrow(MemberConflictException::new);}catch(DataIntegrityViolationException x){throw new MemberConflictException();}}
 public MemberResponse role(UUID t,UUID id,String r){return jdbc.query("UPDATE business_memberships SET role=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=? AND role<>'OWNER' AND status='ACTIVE' RETURNING id,user_id,(SELECT normalized_email FROM users WHERE id=user_id),role,status,(SELECT id FROM employees WHERE tenant_id=? AND user_id=business_memberships.user_id) employee_id,created_at,updated_at",this::map,r,t,id,t).stream().findFirst().orElseThrow(com.bookflow.shared.error.ResourceNotFoundException::new);}
 public boolean revoke(UUID t,UUID id,UUID by){return jdbc.update("UPDATE business_memberships SET status='REVOKED',revoked_at=CURRENT_TIMESTAMP,revoked_by=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=? AND role<>'OWNER' AND status='ACTIVE'",by,t,id)==1;}
 public boolean link(UUID t,UUID m,UUID e){try{return jdbc.update("UPDATE employees x SET user_id=(SELECT user_id FROM business_memberships WHERE tenant_id=? AND id=? AND status='ACTIVE'),updated_at=CURRENT_TIMESTAMP WHERE x.tenant_id=? AND x.id=? AND x.status='ACTIVE' AND (x.user_id IS NULL OR x.user_id=(SELECT user_id FROM business_memberships WHERE tenant_id=? AND id=?))",t,m,t,e,t,m)==1;}catch(DataIntegrityViolationException x){throw new MemberConflictException();}}
 public void unlink(UUID t,UUID m){jdbc.update("UPDATE employees SET user_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND user_id=(SELECT user_id FROM business_memberships WHERE tenant_id=? AND id=?)",t,t,m);}
 private MemberResponse map(ResultSet r,int n)throws SQLException{return new MemberResponse(r.getObject("id",UUID.class),r.getObject("user_id",UUID.class),r.getString("normalized_email"),r.getString("role"),r.getString("status"),r.getObject("employee_id",UUID.class),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());}
}
