spring:
  application:
    name: bookflow-api

bookflow:
  authentication:
    password:
      argon2:
        salt-length: 16
        hash-length: 32
        parallelism: 1
        memory-kib: 19456
        iterations: 2

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
    disable-swagger-default-url: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
