spring:
  config:
    import: "optional:file:../../.env[.properties]"

  datasource:
    url: ${BOOKFLOW_DB_URL:jdbc:postgresql://127.0.0.1:5433/bookflow}
    username: ${BOOKFLOW_DB_USERNAME:bookflow}
    password: ${BOOKFLOW_DB_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: false
    out-of-order: false
    clean-disabled: true

server:
  address: ${BOOKFLOW_API_ADDRESS:127.0.0.1}
  port: ${BOOKFLOW_API_PORT:8080}