'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { activeOnly, useBookFlowMock } from './mock-provider'
import { Empty, Field } from './ui'

export function PublicCatalog({ slug }: { slug: string }) {
  const { branches, employees, services } = useBookFlowMock(); const activeBranches = activeOnly(branches); const [branchId, setBranchId] = useState(activeBranches[0]?.id ?? ''); const [serviceId, setServiceId] = useState('')
  useEffect(() => { if (!activeBranches.some(branch => branch.id === branchId)) setBranchId(activeBranches[0]?.id ?? '') }, [activeBranches, branchId])
  if (slug.toLowerCase() !== 'an-nhien-wellness') return <main className="mx-auto max-w-3xl p-10"><h1 className="font-serif text-4xl font-semibold">Không tìm thấy business.</h1><p className="mt-3 text-muted-foreground">Catalog mock chỉ có slug an-nhien-wellness.</p><Link className="mt-6 inline-block underline" href="/an-nhien-wellness">Mở catalog demo</Link></main>
  const listedServices = activeOnly(services).filter(service => service.branchIds.includes(branchId)); const listedEmployees = activeOnly(employees).filter(employee => employee.branchIds.includes(branchId) && (!serviceId || services.some(service => service.id === serviceId && service.employeeIds.includes(employee.id))))
  return <main className="min-h-screen"><header className="mx-auto flex max-w-6xl items-center justify-between p-5"><Link href="/an-nhien-wellness" className="font-serif text-2xl font-semibold">BookFlow</Link><div className="flex gap-2"><Link href="/login"><Button variant="ghost">Đăng nhập</Button></Link><Link href="/register"><Button>Bắt đầu miễn phí</Button></Link></div></header><section className="bg-primary px-5 py-14 text-primary-foreground"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-widest">Public Catalog</p><h1 className="mt-4 font-serif text-5xl font-semibold">An Nhiên Wellness</h1><p className="mt-3 text-primary-foreground/70">Dữ liệu công khai, không chứa thông tin tenant hoặc membership.</p></div></section><section className="mx-auto max-w-6xl p-5 py-9"><div className="grid gap-4 md:grid-cols-2"><Field label="Chi nhánh"><select value={branchId} onChange={event => { setBranchId(event.target.value); setServiceId('') }} className="h-10 rounded-lg border border-border bg-background px-3">{activeBranches.map(branch => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></Field><Field label="Lọc theo dịch vụ"><select value={serviceId} onChange={event => setServiceId(event.target.value)} className="h-10 rounded-lg border border-border bg-background px-3"><option value="">Tất cả dịch vụ</option>{listedServices.map(service => <option key={service.id} value={service.id}>{service.name}</option>)}</select></Field></div><h2 className="mt-10 font-serif text-3xl font-semibold">Dịch vụ</h2>{listedServices.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{listedServices.map(service => <article key={service.id} className="rounded-2xl border border-border bg-card p-5"><h3 className="font-semibold">{service.name}</h3><p className="mt-1 text-sm text-muted-foreground">{service.description}</p><p className="mt-4 text-sm">{new Intl.NumberFormat('vi-VN').format(Number(service.price))} {service.currency} · {service.durationMinutes} phút</p><Button disabled className="mt-4">Đặt lịch — Sắp ra mắt</Button></article>)}</div> : <Empty>Chi nhánh này chưa có dịch vụ đang hoạt động.</Empty>}<h2 className="mt-10 font-serif text-3xl font-semibold">Đội ngũ</h2>{listedEmployees.length ? <div className="mt-4 grid gap-3 md:grid-cols-3">{listedEmployees.map(employee => <article key={employee.id} className="rounded-2xl border border-border p-5"><div className="grid size-10 place-items-center rounded-full bg-secondary font-semibold">{employee.fullName[0]}</div><h3 className="mt-4 font-semibold">{employee.fullName}</h3><p className="mt-1 text-sm text-muted-foreground">{employee.bio}</p></article>)}</div> : <Empty>Chưa có nhân viên phù hợp.</Empty>}</section></main>
}
