package com.bookflow.employees.application;
import com.bookflow.employees.api.*; import com.bookflow.shared.error.*; import org.springframework.stereotype.Component; import java.util.*; import java.util.regex.Pattern;
@Component public class EmployeeRequestValidator {
 private static final Pattern CODE=Pattern.compile("^[A-Z0-9]+(?:-[A-Z0-9]+)*$"); private static final Pattern PHONE=Pattern.compile("^[+()0-9 .-]{7,30}$"); private static final Pattern EMAIL=Pattern.compile("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$");
 public Values create(CreateEmployeeRequest r){if(r==null)throw fail(List.of(new ApiFieldViolation("$","NotNull","Request body is required."))); List<ApiFieldViolation> v=unknown(r.unknownFields()); Values x=values(r.getCode(),r.getFullName(),r.getPhone(),r.getEmail(),r.getBio(),true,v); if(!v.isEmpty())throw fail(v);return x;}
 public Values update(UpdateEmployeeRequest r){if(r==null)throw fail(List.of(new ApiFieldViolation("$","NotNull","Request body is required.")));List<ApiFieldViolation> v=unknown(r.unknownFields());if(!r.hasKnownField())v.add(new ApiFieldViolation("$","NotEmpty","At least one employee field is required."));Values x=values(r.getCode(),r.getFullName(),r.getPhone(),r.getEmail(),r.getBio(),false,v);if(!v.isEmpty())throw fail(v);return x;}
 private Values values(String code,String name,String phone,String email,String bio,boolean required,List<ApiFieldViolation> v){String c=text(code,"code",50,required,v);if(c!=null){c=c.toUpperCase(Locale.ROOT);if(!CODE.matcher(c).matches())v.add(new ApiFieldViolation("code","Pattern","Employee code format is invalid."));}String n=text(name,"fullName",200,required,v);String p=optional(phone,"phone",30,v);if(p!=null&&!PHONE.matcher(p).matches())v.add(new ApiFieldViolation("phone","Pattern","Phone is invalid."));String e=optional(email,"email",254,v);if(e!=null&&!EMAIL.matcher(e).matches())v.add(new ApiFieldViolation("email","Email","Email is invalid."));String b=optional(bio,"bio",2000,v);return new Values(c,n,p,e,b);}
 private String text(String s,String f,int max,boolean req,List<ApiFieldViolation>v){if(s==null){if(req)v.add(new ApiFieldViolation(f,"NotBlank","Value is required."));return null;}return optional(s,f,max,v);} private String optional(String s,String f,int max,List<ApiFieldViolation>v){if(s==null)return null;String x=s.strip();if(x.isEmpty()||x.length()>max){v.add(new ApiFieldViolation(f,x.isEmpty()?"NotBlank":"Size","Value is invalid."));return null;}return x;} private List<ApiFieldViolation> unknown(Set<String>s){return s.stream().sorted().map(x->new ApiFieldViolation(x,"Forbidden","This field is not allowed.")).collect(java.util.stream.Collectors.toCollection(ArrayList::new));}private RequestValidationException fail(List<ApiFieldViolation>v){return new RequestValidationException(v);} public record Values(String code,String fullName,String phone,String email,String bio){}
}
