'use client'

import { useMemo, useState } from 'react'
import {
  Archive, ArrowUpRight, Bell, BookOpen, Building2, Check, ChevronDown, CircleHelp, ExternalLink,
  LayoutDashboard, Library, Menu, MoreHorizontal, Plus, Search, Settings2, ShieldCheck, Sparkles,
  Store, Users, X, Zap,
} from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'

const navGroups = [
  { label: 'TỔNG QUAN', items: [{ id: 'dashboard', label: 'Tổng quan', icon: LayoutDashboard }] },
  { label: 'VẬN HÀNH', items: [
    { id: 'business', label: 'Thông tin cửa hàng', icon: Store },
    { id: 'branches', label: 'Chi nhánh', icon: Building2 },
    { id: 'employees', label: 'Nhân viên', icon: ShieldCheck },
  ] },
  { label: 'KHÁCH HÀNG', items: [
    { id: 'members', label: 'Thành viên', icon: Users },
    { id: 'services', label: 'Dịch vụ', icon: Library },
  ] },
]

const stats = [
  { label: 'Chi nhánh hoạt động', value: '3', note: 'Tăng 1 trong tháng này', tone: 'mint', icon: Building2 },
  { label: 'Thành viên', value: '1,284', note: '+12.8% so với tháng trước', tone: 'blue', icon: Users },
  { label: 'Dịch vụ đang bán', value: '8', note: '2 dịch vụ đang nháp', tone: 'orange', icon: Zap },
]

const branches = [
  { name: 'BookFlow Nguyễn Huệ', address: '12 Nguyễn Huệ, Quận 1', status: 'Đang hoạt động', members: '542' },
  { name: 'BookFlow Thảo Điền', address: '68 Xuân Thủy, TP. Thủ Đức', status: 'Đang hoạt động', members: '391' },
  { name: 'BookFlow Hải Châu', address: '24 Bạch Đằng, Đà Nẵng', status: 'Đang hoạt động', members: '351' },
]

function Sidebar({ active, setActive, open, setOpen }: { active: string; setActive: (id: string) => void; open: boolean; setOpen: (v: boolean) => void }) {
  return <>
    {open && <button aria-label="Đóng menu" className="fixed inset-0 z-30 bg-foreground/20 lg:hidden" onClick={() => setOpen(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-72 flex-col border-r border-border bg-sidebar transition-transform lg:static lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex h-20 items-center justify-between border-b border-border px-6">
        <div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><BookOpen className="size-5" /></div><div><div className="font-serif text-xl font-semibold tracking-tight">BookFlow</div><div className="text-[11px] font-medium uppercase tracking-widest text-muted-foreground">Quản lý tinh gọn</div></div></div>
        <Button size="icon" variant="ghost" className="lg:hidden" onClick={() => setOpen(false)} aria-label="Đóng menu"><X /></Button>
      </div>
      <div className="border-b border-border p-4"><button className="flex w-full items-center justify-between rounded-xl bg-background px-3 py-3 text-left shadow-sm"><span className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-accent text-accent-foreground"><Store className="size-4" /></span><span><span className="block text-sm font-semibold">Tiệm Sách Mộc</span><span className="block text-xs text-muted-foreground">3 chi nhánh</span></span></span><ChevronDown className="size-4 text-muted-foreground" /></button></div>
      <nav className="flex-1 overflow-y-auto p-4">{navGroups.map((group) => <div key={group.label} className="mb-6"><div className="mb-2 px-3 text-[10px] font-bold tracking-[0.18em] text-muted-foreground">{group.label}</div><div className="flex flex-col gap-1">{group.items.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => { setActive(item.id); setOpen(false) }} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition-colors ${active === item.id ? 'bg-primary text-primary-foreground shadow-sm' : 'text-sidebar-foreground hover:bg-sidebar-accent'}`}><Icon className="size-4" />{item.label}</button> })}</div></div>)}</nav>
      <div className="border-t border-border p-4"><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-sidebar-accent"><Settings2 className="size-4" />Cài đặt tài khoản</button><div className="mt-4 flex items-center gap-3 rounded-xl bg-background p-3"><div className="flex size-9 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">MN</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">Mai Ngọc</div><div className="text-xs text-muted-foreground">Chủ cửa hàng</div></div><MoreHorizontal className="size-4 text-muted-foreground" /></div></div>
    </aside>
  </>
}

function Header({ onMenu }: { onMenu: () => void }) { return <header className="flex h-20 items-center justify-between border-b border-border bg-background px-5 md:px-8"><div className="flex items-center gap-3"><Button size="icon" variant="ghost" className="lg:hidden" onClick={onMenu} aria-label="Mở menu"><Menu /></Button><div><p className="text-xs font-medium uppercase tracking-widest text-muted-foreground">Thứ Hai, 12 tháng 8, 2026</p><h1 className="font-serif text-2xl font-semibold tracking-tight">Chào buổi sáng, Mai</h1></div></div><div className="flex items-center gap-2"><Button size="icon" variant="ghost" aria-label="Tìm kiếm"><Search /></Button><Button size="icon" variant="ghost" aria-label="Thông báo"><Bell /><span className="absolute ml-5 mt-[-14px] size-2 rounded-full bg-accent-foreground" /></Button><Button variant="outline" className="hidden gap-2 sm:flex"><ExternalLink className="size-4" />Trang cửa hàng</Button></div></header> }

function Dashboard({ setActive }: { setActive: (id: string) => void }) {
  const [done, setDone] = useState([true, true, false, false])
  const progress = Math.round((done.filter(Boolean).length / done.length) * 100)
  return <div className="flex flex-col gap-8 p-5 md:p-8"><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><Badge variant="secondary" className="mb-3 rounded-full px-3 py-1 text-accent-foreground"><Sparkles className="mr-1 size-3" />Không gian của bạn</Badge><h2 className="max-w-xl font-serif text-4xl font-semibold leading-tight tracking-tight md:text-5xl">Mọi thứ cho tiệm sách, <span className="text-accent-foreground">gọn gàng hơn.</span></h2><p className="mt-3 max-w-lg text-sm leading-6 text-muted-foreground">BookFlow giúp bạn quản lý cửa hàng, chăm sóc thành viên và phát triển thương hiệu từ một nơi duy nhất.</p></div><Button onClick={() => setActive('business')} className="gap-2 self-start">Chỉnh sửa cửa hàng <ArrowUpRight className="size-4" /></Button></section>
    <section className="grid gap-4 md:grid-cols-3">{stats.map((stat) => { const Icon = stat.icon; return <div key={stat.label} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-start justify-between"><div className={`flex size-10 items-center justify-center rounded-xl ${stat.tone === 'mint' ? 'bg-accent text-accent-foreground' : stat.tone === 'blue' ? 'bg-secondary text-secondary-foreground' : 'bg-muted text-foreground'}`}><Icon className="size-5" /></div><MoreHorizontal className="size-4 text-muted-foreground" /></div><div className="mt-5 text-3xl font-semibold tracking-tight">{stat.value}</div><div className="mt-1 text-sm font-medium">{stat.label}</div><div className="mt-2 text-xs text-muted-foreground">{stat.note}</div></div> })}</section>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_1fr]"><section className="rounded-2xl border border-border bg-card p-5 md:p-6"><div className="flex items-start justify-between gap-4"><div><h3 className="text-lg font-semibold">Thiết lập không gian</h3><p className="mt-1 text-sm text-muted-foreground">Hoàn thiện một vài bước để bắt đầu tốt hơn.</p></div><span className="font-mono text-sm font-semibold text-accent-foreground">{progress}%</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${progress}%` }} /></div><div className="mt-5 flex flex-col gap-2">{['Thêm thông tin cửa hàng', 'Tạo chi nhánh đầu tiên', 'Thêm dịch vụ', 'Mời nhân viên'].map((label, i) => <button key={label} onClick={() => setDone((old) => old.map((v, index) => index === i ? !v : v))} className="flex items-center gap-3 rounded-xl p-3 text-left transition-colors hover:bg-muted"><span className={`flex size-6 items-center justify-center rounded-full border ${done[i] ? 'border-primary bg-primary text-primary-foreground' : 'border-border text-transparent'}`}><Check className="size-3.5" /></span><span className={`text-sm ${done[i] ? 'text-muted-foreground line-through' : 'font-medium'}`}>{label}</span>{!done[i] && <ArrowUpRight className="ml-auto size-4 text-muted-foreground" />}</button>)}</div></section><section className="rounded-2xl border border-border bg-primary p-6 text-primary-foreground"><div className="flex size-10 items-center justify-center rounded-xl bg-primary-foreground/10"><CircleHelp className="size-5" /></div><h3 className="mt-7 font-serif text-2xl font-semibold">Cần một chút hướng dẫn?</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/70">Khám phá cách BookFlow giúp tiệm sách của bạn vận hành nhẹ nhàng hơn mỗi ngày.</p><Button variant="secondary" className="mt-6 gap-2">Xem hướng dẫn <ArrowUpRight className="size-4" /></Button></section></div>
    <section className="rounded-2xl border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-5 md:p-6"><div><h3 className="text-lg font-semibold">Chi nhánh của bạn</h3><p className="mt-1 text-sm text-muted-foreground">Theo dõi nhanh các điểm bán đang hoạt động.</p></div><Button variant="outline" size="sm" onClick={() => setActive('branches')}>Xem tất cả</Button></div><div className="divide-y divide-border">{branches.map((branch) => <div key={branch.name} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-muted"><Building2 className="size-4 text-muted-foreground" /></div><div><div className="text-sm font-semibold">{branch.name}</div><div className="mt-1 text-xs text-muted-foreground">{branch.address}</div></div></div><div className="flex items-center gap-6 pl-13 sm:pl-0"><div><div className="text-sm font-semibold">{branch.members}</div><div className="text-xs text-muted-foreground">thành viên</div></div><Badge variant="outline" className="border-accent text-accent-foreground">{branch.status}</Badge></div></div>)}</div></section>
  </div>
}

function GenericPage({ active, setActive }: { active: string; setActive: (id: string) => void }) {
  const configs: Record<string, { title: string; desc: string; icon: typeof Store; action: string; rows: string[] }> = {
    business: { title: 'Thông tin cửa hàng', desc: 'Xây dựng nền tảng thương hiệu nhất quán cho tiệm sách.', icon: Store, action: 'Lưu thay đổi', rows: ['Tên cửa hàng', 'Mô tả ngắn', 'Địa chỉ liên hệ', 'Giờ mở cửa'] },
    branches: { title: 'Chi nhánh', desc: 'Quản lý địa điểm và thông tin hiển thị của từng chi nhánh.', icon: Building2, action: 'Thêm chi nhánh', rows: branches.map((b) => b.name) },
    employees: { title: 'Nhân viên', desc: 'Phân quyền và theo dõi đội ngũ đang vận hành cửa hàng.', icon: ShieldCheck, action: 'Mời nhân viên', rows: ['Mai Ngọc · Chủ cửa hàng', 'Linh Trần · Quản lý', 'An Nguyễn · Nhân viên'] },
    members: { title: 'Thành viên', desc: 'Nơi bạn xây dựng mối quan hệ lâu dài với khách hàng.', icon: Users, action: 'Thêm thành viên', rows: ['Nguyễn Minh Anh', 'Trần Hoàng Nam', 'Lê Khánh Linh', 'Phạm Gia Hân'] },
    services: { title: 'Dịch vụ', desc: 'Tạo và quản lý những trải nghiệm đặc biệt tại tiệm.', icon: Library, action: 'Tạo dịch vụ', rows: ['Đọc sách tại chỗ', 'Gói thành viên Mộc', 'Gói quà tặng', 'Đặt sách trước'] },
  }
  const config = configs[active] ?? configs.business; const Icon = config.icon
  return <div className="flex flex-col gap-8 p-5 md:p-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-4 flex size-11 items-center justify-center rounded-2xl bg-accent text-accent-foreground"><Icon className="size-5" /></div><h2 className="font-serif text-4xl font-semibold tracking-tight">{config.title}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">{config.desc}</p></div><Button className="gap-2 self-start"><Plus className="size-4" />{config.action}</Button></div><div className="flex flex-col gap-4 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input aria-label="Tìm kiếm" placeholder={`Tìm trong ${config.title.toLowerCase()}...`} className="h-11 w-full rounded-xl border border-input bg-card pl-10 pr-4 text-sm outline-none ring-offset-background focus-visible:ring-2 focus-visible:ring-ring" /></div><Button variant="outline" className="gap-2"><Archive className="size-4" />Bộ lọc</Button></div><section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="hidden grid-cols-[1fr_180px_80px] gap-4 border-b border-border bg-muted/40 px-5 py-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground md:grid"><span>{config.title}</span><span>Trạng thái</span><span /></div>{config.rows.map((row, index) => <div key={row} className="flex flex-col gap-3 border-b border-border p-5 last:border-0 md:grid md:grid-cols-[1fr_180px_80px] md:items-center md:gap-4 md:py-4"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-muted text-xs font-semibold">{index + 1}</div><span className="text-sm font-medium">{row}</span></div><Badge variant={index === 3 && active === 'services' ? 'secondary' : 'outline'} className="w-fit border-accent text-accent-foreground">{index === 3 && active === 'services' ? 'Bản nháp' : 'Đang hoạt động'}</Badge><Button size="icon" variant="ghost" aria-label={`Tùy chọn ${row}`}><MoreHorizontal /></Button></div>)}</section></div>
}

function Catalog() { return <div className="min-h-screen bg-background"><header className="flex items-center justify-between border-b border-border px-5 py-5 md:px-10"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><BookOpen className="size-4" /></div><span className="font-serif text-xl font-semibold">BookFlow</span></div><Button variant="outline" size="sm">Đăng ký thành viên</Button></header><main className="mx-auto flex max-w-6xl flex-col gap-10 px-5 py-12 md:px-10 md:py-20"><div className="max-w-2xl"><Badge variant="secondary" className="mb-4">Tiệm Sách Mộc</Badge><h1 className="font-serif text-5xl font-semibold leading-tight tracking-tight md:text-7xl">Những điều hay ho đang chờ bạn.</h1><p className="mt-5 max-w-lg text-base leading-7 text-muted-foreground">Một góc nhỏ để đọc, học và kết nối. Khám phá dịch vụ dành riêng cho bạn tại chi nhánh gần nhất.</p></div><div className="grid gap-4 md:grid-cols-3">{['Đọc sách tại chỗ', 'Gói thành viên Mộc', 'Gói quà tặng'].map((item, i) => <article key={item} className="rounded-2xl border border-border bg-card p-6"><div className="flex size-10 items-center justify-center rounded-xl bg-accent text-accent-foreground"><BookOpen className="size-5" /></div><h2 className="mt-10 text-lg font-semibold">{item}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Trải nghiệm được thiết kế nhẹ nhàng cho những ngày bạn cần thêm cảm hứng.</p><Button variant="link" className="mt-4 -ml-3 px-3">Tìm hiểu thêm <ArrowUpRight /></Button></article>)}</div></main></div> }

export default function BookFlowApp() {
  const [active, setActive] = useState('dashboard'); const [menuOpen, setMenuOpen] = useState(false); const [catalog, setCatalog] = useState(false)
  const title = useMemo(() => active === 'dashboard' ? 'Tổng quan' : navGroups.flatMap((g) => g.items).find((i) => i.id === active)?.label ?? 'BookFlow', [active])
  if (catalog) return <Catalog />
  return <div className="min-h-screen bg-background text-foreground"><div className="flex min-h-screen"><Sidebar active={active} setActive={setActive} open={menuOpen} setOpen={setMenuOpen} /><div className="min-w-0 flex-1"><Header onMenu={() => setMenuOpen(true)} /><div className="hidden" aria-live="polite">{title}</div>{active === 'dashboard' ? <Dashboard setActive={setActive} /> : <GenericPage active={active} setActive={setActive} />}</div></div><button onClick={() => setCatalog(true)} className="fixed bottom-5 right-5 flex items-center gap-2 rounded-full bg-primary px-4 py-3 text-xs font-semibold text-primary-foreground shadow-lg transition-transform hover:-translate-y-0.5"><ExternalLink className="size-3.5" />Xem catalog công khai</button></div>
}
