package com.bookflow.businesses.members.application;
import com.bookflow.businesses.authorization.*; import com.bookflow.businesses.members.api.*; import com.bookflow.businesses.members.repository.MemberRepository; import com.bookflow.shared.error.*; import org.springframework.context.annotation.Profile; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Profile("!test") public class MemberService { private final TenantAuthorizationService auth; private final MemberRepository repo; public MemberService(TenantAuthorizationService a,MemberRepository r){auth=a;repo=r;}
 public List<MemberResponse> list(UUID u,UUID t){auth.requirePermission(u,t,TenantPermission.MEMBER_VIEW);return repo.list(t);}
 @Transactional public MemberResponse invite(UUID u,UUID t,CreateMemberRequest r){auth.requirePermission(u,t,TenantPermission.MEMBER_MANAGE);if(r==null||r.email()==null||r.role()==null)throw invalid();String role=r.role().trim().toUpperCase(Locale.ROOT);if(!Set.of("ADMIN","STAFF").contains(role))throw invalid();UUID target=repo.userByEmail(r.email().strip().toLowerCase(Locale.ROOT)).orElseThrow(ResourceNotFoundException::new);if(r.employeeId()!=null&&!repo.activeEmployee(t,r.employeeId()))throw new ResourceNotFoundException();MemberResponse m=repo.invite(t,target,role,r.employeeId());if(r.employeeId()!=null&&!repo.link(t,m.id(),r.employeeId()))throw new ResourceNotFoundException();return repo.byId(t,m.id()).orElseThrow(ResourceNotFoundException::new);}
 @Transactional public MemberResponse role(UUID u,UUID t,UUID m,UpdateMemberRoleRequest r){auth.requirePermission(u,t,TenantPermission.MEMBER_MANAGE);if(r==null||r.role()==null||!Set.of("ADMIN","STAFF").contains(r.role().trim().toUpperCase(Locale.ROOT)))throw invalid();return repo.role(t,m,r.role().trim().toUpperCase(Locale.ROOT));}
 @Transactional public void revoke(UUID u,UUID t,UUID m){auth.requirePermission(u,t,TenantPermission.MEMBER_MANAGE);if(!repo.revoke(t,m,u)&&repo.byId(t,m).isEmpty())throw new ResourceNotFoundException();}
 @Transactional public void link(UUID u,UUID t,UUID m,UUID e){auth.requirePermission(u,t,TenantPermission.MEMBER_MANAGE);if(repo.byId(t,m).filter(x->x.status().equals("ACTIVE")).isEmpty()||!repo.activeEmployee(t,e))throw new ResourceNotFoundException();if(!repo.link(t,m,e)&&repo.byId(t,m).map(x->e.equals(x.employeeId())).orElse(false))return;throw new ResourceNotFoundException();}
 @Transactional public void unlink(UUID u,UUID t,UUID m){auth.requirePermission(u,t,TenantPermission.MEMBER_MANAGE);if(repo.byId(t,m).isEmpty())throw new ResourceNotFoundException();repo.unlink(t,m);}
 private RequestValidationException invalid(){return new RequestValidationException(List.of(new ApiFieldViolation("$","Invalid","Member request is invalid.")));}}
